# Generated by Django 6.0.5 on 2026-05-28 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('india_cpi', models.FloatField(blank=True, null=True)),
                ('india_inflation_pct', models.FloatField(blank=True, null=True)),
                ('petrol_price_hyd', models.FloatField(blank=True, null=True)),
                ('rent_index', models.FloatField(blank=True, null=True)),
                ('groceries_index', models.FloatField(blank=True, null=True)),
                ('restaurant_index', models.FloatField(blank=True, null=True)),
                ('fetch_error', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_dummy', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BudgetSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('transport', 'Transport'), ('food', 'Food'), ('healthcare', 'Healthcare'), ('home', 'Home'), ('entertainment', 'Entertainment'), ('subscriptions', 'Subscriptions'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('investment', 'Investment'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('monthly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='budget.monthlybudget')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('monthly_budget', 'category')},
            },
        ),
    ]
