# Generated by Django 6.0.5 on 2026-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, default=38500, max_digits=10)),
                ('emi_amount', models.DecimalField(decimal_places=2, default=28168, max_digits=10)),
                ('emi_end_year', models.IntegerField(default=2028)),
                ('emi_end_month', models.IntegerField(default=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Settings',
            },
        ),
        migrations.AlterField(
            model_name='budgetsplit',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('transport', 'Transport'), ('food', 'Food'), ('healthcare', 'Healthcare'), ('home', 'Home'), ('entertainment', 'Entertainment'), ('subscriptions', 'Subscriptions'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('investment', 'Investment'), ('emi', 'Loan EMI'), ('other', 'Other')], max_length=50),
        ),
    ]
