# Generated by Django 6.0.5 on 2026-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_appsettings_alter_budgetsplit_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
        migrations.AddField(
            model_name='costsnapshot',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='costsnapshot',
            unique_together={('year', 'month', 'location')},
        ),
    ]
